---
- hosts: all
  grub:
    - "net.ifnames=0"
    - "biosdevname=0"
  tasks:
  - name: add grub stuff
    lineinfile:
      dest: /etc/default/grub
      line: {{ item }}
      loop: {{ grub }}
      