---
- hosts: all
  tasks:
  - name: add grub stuff
    lineinfile:
      dest: /etc/default/grub
      line: "{{ item }}"
    loop:
      - "net.ifnames=0"
      - "biosdevname=0"
  - name: run grub2 thingy
    ignore_errors: yes
    shell:
      cmd: grub2-mkconfig
      