---
- hosts: all
  tasks:
  - name: unistall httpd
    yum: name=httpd state=absent
    notify: delete_index
  - name: close ports
    firewalld: state=disabled port=80/tcp
  handlers:
  - name: remove index file
    file: state=absent path=/var/www/html/index.html
    listen: delete_index