---
- hosts: all
  vars_files:
    - secrets.yaml
  tasks:
  - name: setting up users
    user:
      comment: "{{ item.key }}@example.com"
      name: "{{ item.key }}"
      password: "{{ item.value | password_hash('sha512') }}"
    with_dict: "{{ passwords }}""